/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/Book.java
 * Module: Book
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.model;

import lombok.Getter;
import lombok.Setter;
import lombok.AllArgsConstructor;
import lombok.ToString;

@Getter
@Setter
@AllArgsConstructor
@ToString
public class Book {
    private String isbn;
    private String title;
    private String author;
    private Integer publicationYear;
    private Boolean isAvailable;
    
    public Book(String isbn, String title, String author, Integer year) {
        this.isbn = isbn;
        this.title = title;
        this.author = author;
        this.publicationYear = year;
        this.isAvailable = true;
    }
    
    public void displayInfo() {
        System.out.println(toString());
    }
}