/**
 * Automatically translated from Java to Java
 * 
 * Original file: src/main/java/com/example/library/BookController.java
 * Module: BookController
 * 
 * This code was generated by an AI-powered code translation system.
 * Please review and test before using in production.
 */

package com.ssbt.ipp.controller;

import com.converted.app.service.BookService;
import com.converted.app.model.Book;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/books")
public class BookController {
    private final BookService bookService;

    public BookController(BookService bookService) {
        this.bookService = bookService;
    }

    @GetMapping("/{isbn}")
    public ResponseEntity<String> getBook(@PathVariable String isbn) {
        return ResponseEntity.ok("Getting book: " + isbn);
    }

    @PostMapping
    public ResponseEntity<String> addBook(@RequestBody Book book) {
        boolean added = bookService.addBook(book);
        return added ? ResponseEntity.ok("Book added") : ResponseEntity.badRequest().body("Failed to add book");
    }

    @GetMapping("/search")
    public ResponseEntity<String> searchBooks(@RequestParam String query) {
        return ResponseEntity.ok("Searching for: " + query);
    }
}